sudo: required

services:
  - docker

env:
  global:
    - GITHUB_REPO=crazy-max/docker-nextcloud
    - DOCKER_USERNAME=crazymax
    - DOCKER_REPONAME=nextcloud
    - QUAY_USERNAME=crazymax
    - QUAY_REPONAME=nextcloud
    - MICROBADGER_HOOK=https://hooks.microbadger.com/images/crazymax/nextcloud/rCjCdBDz_XNeq8rPpHopWXWxZNI=
    - secure: LVSKcXatL4NI35riS3hmbeeRir7HlWW2ZI187Hmm0ffCe25QKHh8TJWufYPahjHRV5kpY10yUmREgJdM79wT+8RqGgflpbiRS2HECFMUSp0YgdtAL76dsNXJ2ypT9bcLuzndRhVltTkLV/G/tzvygXNXCaPmvF95DwV11JP4I3SC3LskLi9mzet8XocWHlolrV2EXjsC5/Z5dYr+gkLCLtd52PKHH+xjf783f+ZutN8POxwPt6qgraHAiolIehk7BB8tQfnPnzhKixDRZsle24o+23/KLKSguRhg/+SgeMbu5fVAVJWoYBlK5LNlnSgOtSqQHUiytmPmcJm+Jz8GBSVkLdCnp1MXy9+9fRpJbkHr/caKAgTrc/Xv5z2YHa4Zu2jzsP1cerIVCsdMZo9a1lrMmzaWz4RUDxeDXfARC9zMGU47XfZ8azX82jhTf7hlhXP/z/66MZqGJMncsMMc53hI3juKLXTXLCjs5aQl7ivgJUxpgNMyYR7imTDISfWU6vDz4LB5z+BLx4gwwARMdg6UJE1VyKmWKxNMU7Lbjd6LCsmk3Qi2dtkmizcP0cG2y++Vhm+xpjCtDCL4wZIeczrW/sBJOOuASo0IWy6EbjawqEeD6YLRaSrvYH0daOULL1RxQv4J2snWwpnGh2gGym2rvicwOioj6I0ou9HPL0A= # DOCKER_PASSWORD
    - secure: H34bNxpQKfgBJhyW7yv+LXJPEgT4uwZYokLnt8thS5qgGbjvLSX1HuyKKK1q9hwdrQRG+sszU9c32Fj8gCZrI0PQaBXSQDZ/uxMQwCcAF7yubKKat1I/jMrAXnfhUc4bQWiBVmkVr+D5G+JrrIJaJQm04bYrGlDOkHgUeiRn4w9rGXQb6ebr3K7uzE1a82xOSba7qMq8j3xcavQznq5TTJgDkFQyJ/pDhxk9aCfgA3vJ0pgcMX73GayWTGXZUSsxCfWxRMEcKwazkD2spb7PosB9FrWfSOhu2aqPnBigok/h7JNVkHb+WuFIB+HrthMRLvphhD5pS5o5FDXHGOt3lctIyrFNyMurbgzzQnMQG9tWxjoMmvWJLYbfPc9N2svUOXNkq86wnUiR/KkiE1PthfSpQB8zD4lvrC/25bSie7uvTf+uCwGSQCgH+QsKZg12kO7wstzoEdnHJWJBYpZMj1XAS8iBPJKSHnxSa/N40qWp/kiy5HMeJ7OegSdnKoTiXgy5/VNnnIs1NFRlrlvndrzO8XTnKe/1Uvc+bJD1VC+N3FLfaJiqvezec4otf+Abt7ribF1G62RO7p3g4QK1Zk+mOBCDZg4toD4EOVxYaTEVyPQheiDlm8CCJCftlf6bPoBV7jySm08a2E7XcixCDRp2ajoJu+KyUH9i1/yJUGs= # QUAY_PASSWORD
    - secure: kx18US2HSFP2kpSs0WTVd4fLHK1bO+SmfvsWxCsuItv6gI1duJ0f/yb+wXX3cJG1PpJUp3NMDL6hoz8Z/FeqzTvXEK22ikUkFoPURHj6+dzkH+ydYgJS231fw/OKaWu+3cCL+9Y/zuGhFWxewBYzscGzbP7pYPaDOotZROVWsqIx1D4n856oM/qMEHXtGMkXpVP4olr7zWZhe/QpHrzd9zaaBC8g2Mx7rcZsY/MbOrXv0gD6mS/3fJi8WDkqimMNGsP5iYg4K1iNn4g7rXhiIduwIiFWoHmCMyOcIQ6h9QPCfwT4C0CaLPFnnl1DnDh6gR+dhvCOFxJ2H3LtiFYHokiyz5fGQlaw/d4/KMMG71JYwXAnmzpwZFrOoqpoZWTi39qb4gcPhbGHHsOF/0QjXpa+uKyocCVzAWo4S/i9CqWwO+DlcQo0djF7w9nrKFVQRr+/7SKHBKZ22yvKCNBA0MKaC+J7aFnqjf/EcfdBpXeS9yDEFjnsS4qC+EKJK1Ntx299RQ65WqRgfIck3BK0GKrME+ZmGyST2XAVv24TBvq5/BRKNlZ2qNsuOIRyAcbQh0kdezuAZuMzYfrl7MRcr2EOpwPfpd65j+2Dmse6HTNZsWeD/+JAd9WtUTVWMGIt5BG+6GBL8ojrqpQPdrlgPidR0CwLOiTTIjBV6a5ffTk= # GITHUB_TOKEN

before_install:
  - sudo apt-get update
  - docker --version
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - export DOCKER_TAG=$(if [ "$BRANCH" == "master" ]; then echo "latest"; else echo $BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH, DOCKER_TAG=$DOCKER_TAG"

install:
  - |
    docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
      --build-arg VCS_REF=${TRAVIS_COMMIT::8} \
      --build-arg VERSION=${VERSION} \
      -t $DOCKER_USERNAME/$DOCKER_REPONAME -f $DOCKERFILE .

before_script:
  - docker run -d --hostname nextcloud.example.com --name $DOCKER_REPONAME $DOCKER_USERNAME/$DOCKER_REPONAME
  - sleep 20
  - docker logs $DOCKER_REPONAME

script:
  - docker ps | grep $DOCKER_REPONAME

after_success:
  - test $TRAVIS_PULL_REQUEST = false
    && echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    && ($PUSH_LATEST || docker tag $DOCKER_USERNAME/$DOCKER_REPONAME $DOCKER_USERNAME/$DOCKER_REPONAME:$DOCKER_TAG)
    && docker tag $DOCKER_USERNAME/$DOCKER_REPONAME $DOCKER_USERNAME/$DOCKER_REPONAME:$VERSION
    && docker push $DOCKER_USERNAME/$DOCKER_REPONAME
    && echo "$QUAY_PASSWORD" | docker login quay.io --username "$QUAY_USERNAME" --password-stdin
    && ($PUSH_LATEST || docker tag $DOCKER_USERNAME/$DOCKER_REPONAME quay.io/$DOCKER_USERNAME/$DOCKER_REPONAME:$DOCKER_TAG)
    && docker tag $DOCKER_USERNAME/$DOCKER_REPONAME quay.io/$DOCKER_USERNAME/$DOCKER_REPONAME:$VERSION
    && docker push quay.io/$QUAY_USERNAME/$QUAY_REPONAME
    && curl -X POST $MICROBADGER_HOOK

branches:
  except:
    - /^[0-9]/

notifications:
  webhooks:
    secure: h7xfXrtG6sSwkDIPnCStAoBaG73zGyhDs0XeLzuO2KA1sYaIMFQ1FoeUwV7f/Gc2f2Ebo0D44G7hwZwVW955Cr/whgR0ocaafQdoLkPm2mViAwf8Mt/m9Y/RUtntXyvdwD+Y9oWoLSklC+dSy5Tj64lkpjBeIrHAOMZafl6jt7MYJ6vEhCwBkY3UDzlMVo2aRt7WM0dVDYCewbTLyc8trogKUCF+CT2X1vCUfvL7aqKrH3A83uiGyTdql+ISec09tWW3O2coGlmF+q3zkDH9cI2duvk2N5OXh85xRqQY37ZTg0jn91hNvTgMlXo0YdogZtygN6LgMF4ExL/vS2MPGNunRYBRHnDJHhuQnzXGWVk5cNzrcdeYFBtPpJ2X+Jtl00IIRuVTgPXiS8sqQ2zGmjIuCsZhTl1M9xyiceu7yo4Qa6Jl0yuS6Q6UmsvMjKfuy85KYw70LEsmkE8SXsZgRf5SsmoErpFWdt23qD9siPqpw+c1LiyxlpHYp0yABOdp3kKG0eKYcCn+FoaSKpS96UfXAtytQViDU0XeXD7WlnxIbSzjYFXCJg7tix2MrvzX8FL3EoBOFUzAj2dEMhJpANZj0UsuvWgV8muoKXnNg8ev2+y+UBIdfT/VyIbsgGhyoDNIDXfzXRMoz9+FxGtjWeL49fiOdeUY1l87R36NJXg=
