version: '3.2'

services:
  traefik:
    image: traefik:1.6-alpine
    command:
      - --logLevel=INFO
      - --defaultentrypoints=http,https
      - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::443 TLS
      - --docker
      - --docker.exposedbydefault=false
      - --docker.domain=example.com
      - --acme=false
      - --acme.acmelogging=true
      - --acme.email=webmaster@example.com
      - --acme.storage=acme.json
      - --acme.entryPoint=https
      - --acme.onhostrule=true
      - --acme.httpchallenge=true
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ./acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  db:
    image: mariadb:10.2
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=asupersecretpassword
    restart: always

  redis:
    image: redis:4.0-alpine
    restart: always

  app:
    image: crazymax/nextcloud:latest
    depends_on:
      - db
      - redis
    volumes:
      - nextcloud:/data
    labels:
      - traefik.enable=true
      - traefik.backend=nextcloud
      - traefik.port=80
      - traefik.frontend.rule=Host:nextcloud.example.com
    env_file:
      - ./nextcloud.env
    restart: always

  cron:
    image: crazymax/nextcloud:latest
    depends_on:
      - app
    volumes:
      - nextcloud:/data
    command: /usr/local/bin/cron
    env_file:
      - ./nextcloud.env
    environment:
      - CRON_PERIOD=*/15 * * * *
    restart: always

volumes:
  db:
  nextcloud:
